apiVersion: v1
kind: Pod
metadata:
 name: apachepod
 labels:
   app: myapp
spec:
     containers:
         - name: apachecontainer
           image: httpd
           ports:
             - containerPort: 90
